### list of genres
genres = [
    "No Genre Chosen",
    "Action",
    "Adventure",
    "Alternate History",
    "Anthology",
    "Apocalyptic",
    "Autobiography",
    "Biography",
    "Bildungsroman",
    "Business",
    "Children's",
    "Classic",
    "Comedy",
    "Coming of Age",
    "Crime",
    "Cultural",
    "Cyberpunk",
    "Dark Fantasy",
    "Detective",
    "Drama",
    "Dystopian",
    "Epic Fantasy",
    "Erotica",
    "Essay",
    "Fable",
    "Fairy Tale",
    "Family Saga",
    "Fanfiction",
    "Fantasy",
    "Feminist",
    "Food",
    "Gothic",
    "Graphic Novel",
    "Hard Science Fiction",
    "Health",
    "Historical Fiction",
    "Historical Romance",
    "History",
    "Horror",
    "Humor",
    "Inspirational",
    "Legal Thriller",
    "LGBTQ",
    "Literary Fiction",
    "Magical Realism",
    "Memoir",
    "Military",
    "Mystery",
    "Mythology",
    "New Adult",
    "Non-fiction",
    "Paranormal",
    "Philosophy",
    "Poetry",
    "Political",
    "Post-Apocalyptic",
    "Psychological Thriller",
    "Pulp",
    "Realistic Fiction",
    "Reference",
    "Religion",
    "Romance",
    "Satire",
    "Science",
    "Science Fiction",
    "Self-help",
    "Short Story",
    "Space Opera",
    "Speculative Fiction",
    "Spy",
    "Steampunk",
    "Supernatural",
    "Suspense",
    "Technology",
    "Thriller",
    "Time Travel",
    "Travel",
    "Urban Fantasy",
    "Western",
    "Women's Fiction",
    "Young Adult",
]
